### ISSUE TITLE
Put CSS inside <style> tag

### ISSUE THREAD

**Issue by oakmac** [Mikuhl/css-layouts#2]
Please put CSS inside `<style type="text/css">` tags in the .html files in this repo.

**Comment by oakmac** [comment]
This doesn't seem to be done correctly.

I see that  `<link rel="stylesheet" type="text/css" href="style.css">` has been added to the .html files, but there is no corresponding `style.css` file.

The styles that are in the .html files should be either in an external .css file, or inside `<style type="text/css">` tag inside the HTML document.

**Comment by Mikuhl** [comment]
Just updated again. I think I need to clean up directories on my laptop.

**Comment by oakmac** [comment]
Much better :+1:
